### PR TITLE
I1590 - Use docker client rather than shelling out

### PR DESCRIPTION
**Pull request by richfitz**
This also adds some unit tests!  This is my first shot at testing in python.  Run the tests with

```
nosetests3
```

I don't think we're using any testing frameworks elsewhere in the python codebase - if so please point me at it and I'll update things.  The main module used is in the python stdlib so no extra deps here.

### CODE REVIEW

**Comment by hillalex** [comment]
Just to note, changing to the docker client is also part of this PR: https://github.com/vimc/bb8/pull/13/files

A couple of differences between the 2 implementations, - the logic to check if a volume exists and where the docker client comes from. Which do you think are  better?

**Comment by richfitz** [comment]
That's a loaded question :grinning: 

In #13, this line needs removing: https://github.com/vimc/bb8/pull/13/files#diff-d31d39618fbc8025118cb5d12a6e046bR42 and I think https://github.com/vimc/bb8/pull/13/files#diff-d31d39618fbc8025118cb5d12a6e046bR36 is possibly less pythonic? Both fix a logic error (see e350fa3e28c8e09e5a74ba45991fea27a184ae66)

**Comment by richfitz** [comment]
But either way I think getting us started with some tests will be a good idea...

**Comment by hillalex** [comment]
Haha, yes agreed re the duplicate line. I was asking about the checking volume exists logic precisely because I wasn't sure which was more 'pythonic'! In the C# world using `try/catch` to control flow is frowned upon, but it seems to be common in python?

**Comment by hillalex** [comment]
Very much pro getting started with tests! Should the `nosetests3` be added to `requirements.txt`?

**Comment by richfitz** [comment]
According to this: https://stackoverflow.com/questions/18426342/should-i-include-sphinx-and-or-nose-in-my-modules-requirements-txt we possibly should not include development dependencies in the requirements.txt, but we probably should have a second requirements file for tests

**Comment by hillalex** [comment]
That makes sense. Want to add info about how to run tests in the README?

**Comment by richfitz** [comment]
Done!

**Review by hillalex — APPROVED** [review]

**Pull request merged**
